name: minimalTemplate
author: Ajenti project
email: e@ajenti.org
url: https://ajenti.org
version: '1.00'
title: 'minimalTemplate'
icon: bar-chart
dependencies:
    - !PluginDependency { plugin_name: core }
resources:
    - path: ''
