name: core
author: Ajenti project
email: e@ajenti.org
url: https://ajenti.org
version: '1.00'
title: Core
icon: link
requires-angular-build: true
dependencies: [ ]
resources:
  - ng:core
  - ng:core.templates
