name: tryout
author: Arnaud Kientz
email: arnaud@linuxmuster.net
url: https://ajenti.org
docs: https://docs.ajenti.org/en/latest/plugins/fstab.html
version: '0.4'
title: 'Tryout'
icon: hdd
requires-angular-build: true
frontend-settings:
    remote-entry: 'http://localhost:4204/remoteEntry.js' # For debug purposes. Keep empty for production!
    remote-name: 'tryout'
    exposed-module: './Module'
    display-name: 'Tryout'
    route-path: 'tryout'
    ng-module-name: 'TryoutModule'
dependencies:
    - !PluginDependency { plugin_name: core }
resources:
    - path: frontend/dist/vendor.js
      vendor: true
    - frontend/dist/polyfills.js
    - frontend/dist/runtime.js
    - frontend/dist/styles.css
    - frontend/dist/main.js
    - ng:ajenti.tryout
