#!/bin/sh
#DEBHELPER#
update-rc.d ajenti defaults > /dev/null
ajenti-ssl-gen `hostname` || true

echo ------------------------------------------------
echo Now start Ajenti with \'service ajenti start\'
echo Ajenti will listen on HTTPS port 8000 by default
echo 
echo Default username : root
echo Default password : admin
echo ------------------------------------------------
