#!/bin/bash
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
exit 1
fi
echo ':: Adding Ajenti repo'
rpm -ivh http://repo.ajenti.org/ajenti-repo-1.0-1.noarch.rpm
echo ':: Installing package'
zypper in ajenti --non-interactive
echo ':: Done! Open https://<address>:8000 in browser'
