#!/bin/sh

# PROVIDE: ajenti
# REQUIRE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="ajenti"
command="ajenti-panel"
start_cmd="ajenti-panel -d"
procname="/usr/local/bin/ajenti-panel"
command_interpreter="/usr/local/bin/python"

load_rc_config $name
run_rc_command "$1"