#!/bin/sh

### BEGIN INIT INFO
# Provides:          ajenti
# Required-Start:    $network $syslog $local_fs
# Required-Stop:     $network $syslog $local_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ajenti
# Description:       Ajenti administration frontend
### END INIT INFO

. /lib/lsb/init-functions

NAME=Ajenti
DAEMON=/usr/bin/ajenti-panel
PIDFILE=/var/run/ajenti.pid

#test -x $DAEMON || exit 5

case "$1" in
	start)
		echo "Starting $NAME:"
        if pidofproc -p $PIDFILE $DAEMON; then
            log_failure_msg "already running"
            exit 1
        fi
		if $DAEMON -d ; then
            log_success_msg "started"
		else
            log_failure_msg "failed"
		fi
		;;
	stop)
        echo "Stopping $NAME:"
        if pidofproc -p $PIDFILE $DAEMON; then
            killproc -p $PIDFILE $DAEMON
			/bin/rm -rf $PIDFILE
            log_success_msg "stopped"
		else
		   log_failure_msg "not running"
		fi
		;;
	restart)
  		$0 stop && sleep 2 && $0 start
		;;
 	status)
        if pidofproc -p $PIDFILE $DAEMON; then
            log_success_msg "$NAME is running"
        else
            log_success_msg "$NAME is not running"
   		fi
  		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1 
esac

exit 0
