#!/bin/sh

### BEGIN INIT INFO
# Provides:          ajenti
# Required-Start:    $network $syslog $local_fs
# Required-Stop:     $network $syslog $local_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ajenti
# Description:       Ajenti administration frontend
### END INIT INFO

. /lib/lsb/init-functions

NAME=Ajenti
DAEMON=/usr/bin/ajenti-panel
PIDFILE=/var/run/ajenti.pid

#test -x $DAEMON || exit 5

case "$1" in
	start)
		if [ -e $PIDFILE ]; then
			if [ kill -0 `cat $PIDFILE` ]; then
                echo "$NAME is already running!"
				exit 1
			fi
		fi
		echo "* Starting" "$NAME"
		if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- -d ; then
            echo ""
		else
            echo 'Failed!'
		fi
		;;
	stop)
        echo "* Stopping" "$NAME"
		if [ -e $PIDFILE ]; then
            if [ kill -0 `cat $PIDFILE` ]; then
				start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
				/bin/rm -rf $PIDFILE
            else
                echo "$NAME is not running!"
			fi
		else
		   echo "$NAME is not running!"
		fi
		;;
	restart)
  		$0 stop && sleep 2 && $0 start
		;;
 	status)
  		if [ -e $PIDFILE ]; then
            if [ kill -0 `cat $PIDFILE` ]; then
                echo "$NAME is running"
            else
                echo "$NAME is not running"
            fi
  		else
   			echo "$NAME is not running"
   		fi
  		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1 
esac

exit 0
